apiVersion: v1
kind: ConfigMap
metadata:
  name: blazor-web-app-configmap
  namespace: express-messenger
data:
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: in_memory
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
  OTEL_EXPORTER_OTLP_ENDPOINT: http://aspire-dashboard.express-messenger:18889
  OTEL_SERVICE_NAME: blazor-web-app
  Apis__UsersManagement__Url: http://gateway.express-messenger/api/users-management
  Apis__Chatting__Url: http://gateway.express-messenger/api/chatting
