---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: express-messenger
spec:
  type: ClusterIP
  selector:
    app: gateway
  ports:
    - name: http
      port: 80
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-load-balancer
  namespace: express-messenger
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.197
  selector:
    app: gateway
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
