namespace ExpressMessenger.SharedKernel.ApiContracts.UsersManagement.Users.GetUsersDisplayNumbers;

public sealed record GetUsersDisplayNumbersResponse(IReadOnlyDictionary<Guid, uint> DisplayNumbers);