apiVersion: v1
kind: ConfigMap
metadata:
  name: chatting-api-configmap
  namespace: express-messenger
data:
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: in_memory
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
  HTTP_PORTS: "8080"
  OTEL_EXPORTER_OTLP_ENDPOINT: http://aspire-dashboard:18889
  OTEL_SERVICE_NAME: chatting-api
  ASPNETCORE_URLS: http://+:8080;
