---
apiVersion: v1
kind: Service
metadata:
  name: chatting-api
  namespace: express-messenger
spec:
  type: ClusterIP
  selector:
    app: chatting-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
