apiVersion: v1
kind: ConfigMap
metadata:
  name: users-management-api-configmap
  namespace: express-messenger
data:
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: in_memory
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
  OTEL_EXPORTER_OTLP_ENDPOINT: http://aspire-dashboard.express-messenger:18889
  OTEL_SERVICE_NAME: users-management-api
