@UsersManagementApi = http://localhost:5700

POST {{UsersManagementApi}}/api/users-management/users/usernames/validate
Accept: application/json
Content-Type: application/json

{
    "userName": "test123"
}
