name: "Deploy K8S Namespace"
on:
  push:
    branches: ["master"]
    paths:
      [
        "infra/*.namespace.yaml",
        ".github/workflows/namespace.build-and-deploy.yaml",
      ]
  workflow_dispatch:
jobs:
  deploy:
    name: "Deploy K8S Namespace"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: "Copy Kubernetes files to server"
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          proxy_host: ${{ secrets.PROXY_SSH_HOST }}
          proxy_username: ${{ secrets.PROXY_SSH_USERNAME }}
          proxy_password: ${{ secrets.PROXY_SSH_PASSWORD }}
          proxy_port: ${{ secrets.PROXY_SSH_PORT }}
          source: "infra/*.namespace.yaml"
          target: /home/${{ secrets.SSH_USERNAME }}/github/express-messenger/k8s
          strip_components: 1

      - name: "Apply Kubernetes files"
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          proxy_host: ${{ secrets.PROXY_SSH_HOST }}
          proxy_username: ${{ secrets.PROXY_SSH_USERNAME }}
          proxy_password: ${{ secrets.PROXY_SSH_PASSWORD }}
          proxy_port: ${{ secrets.PROXY_SSH_PORT }}
          script: |
            echo ${{ secrets.SSH_PASSWORD }} | sudo cd /home/${{ secrets.SSH_USERNAME }}/github/express-messenger/k8s

            for FILE in $(ls -1 *.yaml | sort); do
                if [ -f "$FILE" ]; then
                    echo ${{ secrets.SSH_PASSWORD }} | sudo -S microk8s kubectl apply -f "$FILE"
                fi
            done

            echo ${{ secrets.SSH_PASSWORD }} | sudo -S rm -rf /home/${{ secrets.SSH_USERNAME }}/github/express-messenger/k8s
